### ISSUE TITLE
Remove wavy line

### ISSUE THREAD

**Issue by kerim** [mlanza/logseq-wide-eyed#4]
Is it possible to remove the following code?

```
    opened: logseq.settings.opened || "text-decoration: underline wavy;"
```

I really love this plugin, but the wavy lines really interfere with my ability to read text when I'm not hiding completed tasks. I would prefer not to have any additional styles applied to them other than what is already in the theme I'm using. Thanks.

**Comment by kerim** [comment]
Never mind, I found your other plugin that allows the user to do this.

**Comment by mlanza** [comment]
@kerim - glad you got it.  Yeah, Style Carousel improves on what you get with Wide Eyed.  By default it toggles the visibility of todos, just like Wide Eyed.  But it does so using information already found in the DOM.  All this means is it doesn't have to query/poll your datastore, which means it has less overhead to run.

I'm planning on retiring Wide Eyed eventually as Style Carousel does the same (and more) but better.
