### ISSUE TITLE
No "eye" icon in toolbar

### ISSUE THREAD

**Issue by nnja** [mlanza/logseq-wide-eyed#5]
After installing the plugin in logseq Version 0.7.9 (0.7.9) an eye icon does not appear in the toolbar, even after closing logseq and reopening it.

**Comment by mlanza** [comment]
I may retire this plugin.  I've written another, [Style Carousel](https://github.com/mlanza/logseq-style-carousel), which provides the same feature using a different mechanism.  Please give it a try for now and let me know how well it meets your need.

**Comment by mlanza** [comment]
I just pushed v2 of Wide Eyed today.  Internally it is Style Carousel.  So it has a new set of configurations and it may have a slightly new behavior.  Consider this a compromise to my not retiring the plugin.  I use Style Carousel daily and it works.  So it should get you what you want.

**Comment by mlanza** [comment]
Please look to Style Carousel (it is the successor of Wide Eyed) and direct any issue you might have there.  Thank you.
